server:
  port: 9101



#turbine:
#  app-config: piclibapi,piclibweb,piclibwap  #  配置Eureka中的serviceId列表，表明监控哪些服务, 启动后从配置中心中进行更新
#  aggregator:
#    cluster-config: default     #  指定聚合哪些集群，多个使用","分割，默认为default。
#  cluster-name-expression: new String("default")   #表示集群的名字为default
#  combine-host-port: true    # 表示同一主机上的服务通过host和port的组合来进行区分，默认情况下是使用host来区分，这样会使本地调试有问题